[package]
name = "cos_sim"
version = "0.1.0"
authors = ["VanillaBrooks <brookskarlik@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "example"
crate-type = ["cdylib"]

[dependencies]
hashbrown = "0.1.8"
parking_lot = "0.7.1"
rayon = "1.0.3"
cbindgen = "0.8.0"
