[package]
name = "pycode"
version = "0.1.0"
authors = ["VanillaBrooks <brookskarlik@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.8"


[dependencies]
hashbrown = "0.1.8"
parking_lot = "0.7.1"
rayon = "1.0.3"
